### ISSUE TITLE
点击登录地址后跳转404 page not found

### ISSUE THREAD

**Issue by bbanned** [AnnonaOrg/tgfaka#6]
tgfaka    | [GIN] 2024/09/17 - 01:46:11 | 302 |    1.164309ms |   193.246.164.2 | GET      "/api/admin/token_login?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjY1MDg4MjksImxvZ2luVXNlcm5hbWUiOiI2MTczNTU5OTgifQ.YM4IRwTXItODZS_GaByC47BDtfNzAy8SsNwz6if97is"
tgfaka    | [GIN] 2024/09/17 - 01:46:11 | 200 |    4.940318ms |   193.246.164.2 | GET      "/page/admin/"
tgfaka    | [GIN] 2024/09/17 - 01:46:12 | 200 |    2.844383ms |   193.246.164.2 | GET      "/res/sdk/iconfont.css"
tgfaka    | [GIN] 2024/09/17 - 01:46:12 | 200 |   18.609829ms |   193.246.164.2 | GET      "/res/sdk/sdk.css"
tgfaka    | [GIN] 2024/09/17 - 01:46:12 | 200 |   12.197017ms |   193.246.164.2 | GET      "/res/sdk/helper.css"
tgfaka    | [GIN] 2024/09/17 - 01:46:12 | 200 |   19.381747ms |   193.246.164.2 | GET      "/res/sdk/sdk.js"
tgfaka    | time="2024-09-17 01:46:12 CST" level=info msg="开始获取TRON交易"
tgfaka    | [GIN] 2024/09/17 - 01:46:12 | 200 |     861.226µs |   193.246.164.2 | GET      "/res/sdk/thirds/@fortawesome/fontawesome-free/webfonts/fa-brands-400.woff2"
tgfaka    | [GIN] 2024/09/17 - 01:46:12 | 200 |     261.796µs |   193.246.164.2 | POST     "/api/admin/info"
tgfaka    | [GIN] 2024/09/17 - 01:46:12 | 200 |    2.898675ms |   193.246.164.2 | GET      "/res/sdk/thirds/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2"
tgfaka    | [GIN] 2024/09/17 - 01:46:12 | 200 |     151.529µs |   193.246.164.2 | POST     "/api/admin/dashboard"
tgfaka    | [GIN] 2024/09/17 - 01:46:13 | 200 |   15.100914ms |   193.246.164.2 | GET      "/res/sdk/charts.js"
tgfaka    | [GIN] 2024/09/17 - 01:46:13 | 200 |      98.075µs |   193.246.164.2 | POST     "/api/admin/dashboard_chart"
tgfaka    | [GIN] 2024/09/17 - 01:46:13 | 404 |         713ns |   193.246.164.2 | GET      "/index/"

**Comment by dbidib** [comment]
后台绑定的域名，需要添加TLS证书，可以直接在配置文件中以 `https://` 开头设置`host`
